# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Zig Compiler
        # You may pin to the exact commit or the version.
        # uses: goto-bus-stop/setup-zig@7ab2955eb728f5440978d5824358023be3a2802d
        uses: goto-bus-stop/setup-zig@v2.2.1
        with:
          # Version of the zig compiler to use (must be 0.3.0 or up)
          version: master # default is master
          # Cache downloaded compilers for faster action runs. Strongly recommended.
          cache: true # optional, default is true
          

      # Runs a single command using the runners shell
      - name: Build and Test
        run: zig build test --summary all
